using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;

namespace Cutout;

public sealed partial class TemplateSourceGenerator
{
    private static void WriteTemplateMethod(
        IndentedTextWriter writer,
        TemplateMethodDetails model,
        bool includeWhitespaceReceiver
    )
    {
        WriteNamespaceParts(writer, model);

        writer.WriteLine();

        WriteAccessibility(writer, model.ClassDetails.ClassSymbol.DeclaredAccessibility);
        writer.Write("static partial class ");
        writer.Write(model.ClassDetails.Name);
        writer.WriteLine();

        writer.WriteLine("{");
        using (writer.Indent())
        {
            WriteAccessibility(writer, model.ClassDetails.ClassSymbol.DeclaredAccessibility);
            writer.Write(includeWhitespaceReceiver ? "static void " : "static partial void ");
            writer.Write(model.MethodDetails.Name);
            writer.Write("(this ");
            for (var index = 0; index < model.MethodDetails.MethodSymbol.Parameters.Length; index++)
            {
                var parameter = model.MethodDetails.MethodSymbol.Parameters[index];
                writer.Write(parameter.Type.Name);
                writer.Write(" ");
                writer.Write(parameter.Name);

                if (index < model.MethodDetails.MethodSymbol.Parameters.Length - 1)
                {
                    writer.Write(", ");
                }
            }

            writer.WriteLine(includeWhitespaceReceiver ? ", string whitespace)" : ")");

            writer.WriteLine("{");
            using (writer.Indent())
            {
                WriteTemplate(writer, model, includeWhitespaceReceiver);
            }
            writer.WriteLine("}");
        }
        writer.WriteLine("}");
    }

    private static void WriteAccessibility(IndentedTextWriter writer, Accessibility accessibility)
    {
        switch (accessibility)
        {
            case Accessibility.Public:
                writer.Write("public ");
                break;
            case Accessibility.Internal:
                writer.Write("internal ");
                break;
            case Accessibility.Private:
                writer.Write("private ");
                break;
            case Accessibility.Protected:
                writer.Write("protected ");
                break;
            case Accessibility.ProtectedOrInternal:
                writer.Write("protected internal ");
                break;
            default:
                throw new ArgumentOutOfRangeException(
                    nameof(accessibility),
                    accessibility,
                    message: "Invalid accessibility"
                );
        }
    }

    private static void WriteTemplate(
        IndentedTextWriter writer,
        TemplateMethodDetails model,
        bool includeWhitespaceReceiver
    )
    {
        var template = model.AttributeDetails.Template;

        if (template is null)
        {
            return;
        }

        Syntax? lastSyntax = null;
        foreach (var syntax in model.AttributeDetails.Syntaxes)
        {
            writer.WriteSyntax(template, syntax, lastSyntax, includeWhitespaceReceiver);
            lastSyntax = syntax;
        }
    }

    private static void WriteNamespaceParts(IndentedTextWriter writer, TemplateMethodDetails model)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        foreach (
            var usingDirective in model
                .Usings.Select(u => u.ToString())
                .Distinct(StringComparer.Ordinal)
                .OrderBy(u => u, StringComparer.Ordinal)
        )
        {
            writer.WriteLine(usingDirective);
        }

        writer.WriteLine();
        writer.Write("namespace ");
        writer.Write(model.Namespace);
        writer.WriteLine(";");
    }
}
