using System.CodeDom.Compiler;
using Cutout.Extensions;

namespace Cutout;

public sealed partial class TemplateSourceGenerator
{
    private static void WriteTemplateMethod(IndentedTextWriter writer, TemplateMethodDetails model)
    {
        WriteNamespaceParts(writer, model);

        writer.WriteLine();

        writer.Write("public static partial class ");
        writer.Write(model.ClassName);
        writer.WriteLine();

        writer.WriteLine("{");
        using (writer.Indent())
        {
            writer.Write("public static partial void ");
            writer.Write(model.MethodDetails.Name);
            writer.Write("(this ");
            for (var index = 0; index < model.MethodDetails.MethodSymbol.Parameters.Length; index++)
            {
                var parameter = model.MethodDetails.MethodSymbol.Parameters[index];
                writer.Write(parameter.Type.Name);
                writer.Write(" ");
                writer.Write(parameter.Name);

                if (index < model.MethodDetails.MethodSymbol.Parameters.Length - 1)
                {
                    writer.Write(", ");
                }
            }

            writer.WriteLine(")");

            writer.WriteLine("{");
            using (writer.Indent())
            {
                WriteTemplate(writer, model);
            }
            writer.WriteLine("}");
        }
        writer.WriteLine("}");
    }

    private static void WriteTemplate(IndentedTextWriter writer, TemplateMethodDetails model)
    {
        var template = model.AttributeDetails.Template;

        if (template is null)
        {
            return;
        }

        foreach (var syntax in model.AttributeDetails.Syntaxes)
        {
            writer.WriteSyntax(syntax);
        }
    }

    private static void WriteNamespaceParts(IndentedTextWriter writer, TemplateMethodDetails model)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        foreach (
            var usingDirective in model
                .Usings.Select(u => u.ToString())
                .Distinct(StringComparer.Ordinal)
                .OrderBy(u => u, StringComparer.Ordinal)
        )
        {
            writer.WriteLine(usingDirective);
        }

        writer.WriteLine();
        writer.Write("namespace ");
        writer.Write(model.Namespace);
        writer.WriteLine(";");
    }
}
