//HintName: Test.FileTest.g.cs
// <auto-generated/>
#nullable enable

using Fluidic;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

public static partial class Test
{
    public static partial void FileTest(this StringBuilder builder)
    {
        builder.Append(@"This is a very simple example

This is a new line
And so is this

Let's add some more lines");
    }
}
