//HintName: Test.Test.g.cs
// <auto-generated/>
#nullable enable

using Fluidic;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

public static partial class Test
{
    public static partial void Test(this StringBuilder builder, String product)
    {
        builder.Append(@"This is a test for tags [");
        for (var i = 0; i < product.Tags.Length; i++)
        {
            if (product.Tags[i] == "awesome")
            {
                continue;
            }
            else if (product.Tags[i] == "shoes")
            {
                break;
            }
            builder.Append(i + 1);
            builder.Append(@". ");
            builder.Append(product.Tags[i]);
        }
        builder.Append(@"] which is cool.");
    }
}
