//HintName: Test.Test.g.cs
// <auto-generated/>
#nullable enable

using Fluidic;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

public static partial class Test
{
    public static partial void Test(this StringBuilder builder, String product)
    {
        builder.Append(@"This is a test for tags [");
        while (i < product.Tags.Length)
        {
            builder.Append(i + 1);
            builder.Append(@". ");
            builder.Append(product.Tags[i++]);
        }
        builder.Append(@"] which is cool.");
    }
}
