using System;
using System.Linq;
using Fluidic.Extensions;

namespace Fluidic;

public sealed partial class StringTemplateSourceGenerator
{
    private static string RenderTemplateMethod(TemplateMethodDetails model)
    {
        return $$"""
            {{RenderNamespaceParts(model)}}

            public static partial class {{model.ClassName}}
            {
                public static partial void {{model.MethodDetails.Name}}(this StringBuilder builder)
                {
                    builder.Append({{model.AttributeDetails.Template}});
                }
            }
            """;
    }

    private static string RenderNamespaceParts(TemplateMethodDetails model)
    {
        return $"""
                // <auto-generated/>
                #nullable enable

                {model
                    .Usings.OrderBy(x => x.Name?.ToString(), StringComparer.Ordinal)
                    .Select(x => x.ToString())
                    .Distinct(StringComparer.Ordinal)
                    .JoinBy("\n")
                }

                namespace {model.Namespace};
                """;
    }
}
