namespace Fluidic;

public sealed partial class StringTemplateSourceGenerator
{
    private const string StringTemplateAttributeSourceCode = """
        #if !FLUIDIC_EXCLUDE_ATTRIBUTES

        // <auto-generated/>
        #nullable enable

        using System;

        namespace Fluidic;

        /// <summary>
        /// Marks a method as a string template generator, this method will be implemented to write
        /// into a string builder like object, based on a provided liquid/scribben template
        /// </summary>
        [AttributeUsage(AttributeTargets.Method)]
        internal sealed class StringTemplateAttribute : Attribute
        {
            /// <summary>
            /// The template to use for generating the builder code
            /// </summary>
            public string? Template { get; set; }
            
            /// <summary>
            /// Initializes a new instance of the <see cref="StringTemplateAttribute"/> class
            /// </summary>
            public StringTemplateAttribute(string template)
            {
                Template = template;
            }
            
            /// <summary>
            /// Initializes a new instance of the <see cref="StringTemplateAttribute"/> class
            /// </summary>
            public StringTemplateAttribute()
            {
            }
        }
        #endif
        """;
}
