//HintName: Test.Test.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static partial void Test(this StringBuilder builder, string product)
    {
        builder.Append(@"Some text before ");
        Case2(builder, product);
    }
}
