//HintName: Test.Test.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

public static partial class Test
{
    public static partial void Test(this StringBuilder builder, String product)
    {
        builder.Append(@"This is a test for tags [");
        foreach (var tag in product.Tags)
        {
            builder.Append(tag);
            builder.Append(@"; ");
        }
        builder.Append(@"] which is cool.");
    }
}
