//HintName: Test.Test.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static partial void Test(this StringBuilder builder, string product)
    {
        builder.Append(@"This is a test for tags [");
        for (var  i = 0; i < product.Tags.Length; i++ )
        {
            if ( product.Tags[i] == "awesome" )
            {
                continue;
            }
            else if ( product.Tags[i] == "shoes" )
            {
                break;
            }
            builder.Append(i + 1);
            builder.Append(@". ");
            builder.Append( product.Tags[i] );
        }
        builder.Append(@"] which is cool.");
    }
}
