//HintName: Test.Test.wsr.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static void Test(this StringBuilder builder, String product, string whitespace)
    {
        builder.Append(@"This is a test for tags [");
        foreach (var tag in product.Tags)
        {
            builder.Append(tag);
            if ((tag).ToString().IndexOf('\n') != -1)
            {
                builder.Append(whitespace);
            }
            builder.Append(@"; ");
        }
        builder.Append(@"] which is cool.");
    }
}
