//HintName: Test.Test.wsr.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static void Test(this StringBuilder builder, String product, string whitespace)
    {
        builder.Append(@"This is a test for tags [");
        for (var i = 0; i < product.Tags.Length; i++)
        {
            if (product.Tags[i] == "awesome")
            {
                continue;
            }
            else if (product.Tags[i] == "shoes")
            {
                break;
            }
            builder.Append(i + 1);
            if ((i + 1).ToString().IndexOf('\n') != -1)
            {
                builder.Append(whitespace);
            }
            builder.Append(@". ");
            builder.Append(product.Tags[i]);
            if ((product.Tags[i]).ToString().IndexOf('\n') != -1)
            {
                builder.Append(whitespace);
            }
        }
        builder.Append(@"] which is cool.");
    }
}
