//HintName: Test.Test.wsr.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static void Test(this StringBuilder builder, string product, string whitespace)
    {
        builder.Append(@"This is a test for tags [");
        while ( i < product.Tags.Length )
        {
            builder.Append(Cutout.RenderUtilities.ApplyExtraWhitespace(i + 1, whitespace));
            builder.Append(@". ");
            builder.Append(Cutout.RenderUtilities.ApplyExtraWhitespace( product.Tags[i++] , whitespace));
        }
        builder.Append(@"] which is cool.");
    }
}
