//HintName: Test.Test.wsr.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static void Test(this StringBuilder builder, string product, string whitespace)
    {
        builder.Append(@"This is a test for tags [");
        foreach (var  tag in product.Tags )
        {
            builder.Append(Cutout.RenderUtilities.ApplyExtraWhitespace(tag, whitespace));
            builder.Append(@"; ");
        }
        builder.Append(@"] which is cool.");
    }
}
