//HintName: Test.Test.wsr.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static void Test(this StringBuilder builder, string product, string whitespace)
    {
        if ( product == "Awesome Shoes" )
        {
            builder.Append(@" These shoes are awesome! ");
        }
        else
        {
            builder.Append(@" These shoes are not awesome! ");
        }
    }
}
