//HintName: TemplateAttribute.g.cs
#if !CUTOUT_EXCLUDE_ATTRIBUTES

// <auto-generated/>
#nullable enable

using System;

namespace Cutout;

/// <summary>
/// Marks a method as a template generator, this method will be implemented to write
/// into a string builder like object, based on a provided compile time known template
/// </summary>
[AttributeUsage(AttributeTargets.Method)]
internal sealed class TemplateAttribute : Attribute
{
    /// <summary>
    /// The template to use for generating the builder code
    /// </summary>
    public string? Template { get; set; }
    
    /// <summary>
    /// Initializes a new instance of the <see cref="TemplateAttribute"/> class
    /// </summary>
    public TemplateAttribute(string template)
    {
        Template = template;
    }
    
    /// <summary>
    /// Initializes a new instance of the <see cref="TemplateAttribute"/> class
    /// </summary>
    public TemplateAttribute()
    {
    }
}
#endif