//HintName: RenderUtilities.g.cs
// <auto-generated/>
#nullable enable

using System;

namespace Cutout;

/// <summary>
/// Utility methods for use in generated render methods
/// </summary>
internal static class RenderUtilities
{
    internal static string? ApplyExtraWhitespace<T>(T value, string whitespace)
    {
        string? str = value switch
        {
            null => null,
            string str1 => str1,
            _ => value.ToString()
        };

        return str is null ? null : str.Replace("\n", "\n" + whitespace);
    }
}
