//HintName: FileTemplateAttribute.g.cs
#if !CUTOUT_EXCLUDE_ATTRIBUTES

// <auto-generated/>
#nullable enable

namespace Cutout;

/// <summary>
/// Marks a method as a template generator based on an external file, this method will be implemented to write
/// into a string builder like object, based on a template defined in an external file
/// </summary>
[AttributeUsage(AttributeTargets.Method)]
internal sealed class FileTemplateAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="FileTemplateAttribute"/> class
    /// </summary>
    public FileTemplateAttribute() {}
}

#endif
