//HintName: Test.Test.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

public static partial class Test
{
    public static partial void Test(this StringBuilder builder)
    {
        builder.Append(@"This is a very simple example");
    }
}
