//HintName: Test.TestWithConstantTemplate.wsr.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static void TestWithConstantTemplate(this StringBuilder builder, SomeModel model, string whitespace)
    {
        builder.Append(Cutout.RenderUtilities.ApplyExtraWhitespace(@"This is an example of a template that is defined in a constant string.

", whitespace));
        if ( model.Value > 0 )
        {
            builder.Append(@"The result is positive.");
        }
        else
        {
            builder.Append(@"The result is negative.");
        }
    }
}
