//HintName: Test.TestWithConstantTemplate.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

public static partial class Test
{
    public static partial void TestWithConstantTemplate(this StringBuilder builder, SomeModel model)
    {
        builder.Append(@"This is an example of a template that is defined in a constant string.

");
        if (model.Value > 0)
        {
            builder.Append(@"The result is positive.");
        }
        else
        {
            builder.Append(@"The result is negative.");
        }
    }
}
