//HintName: Test.TestWithModel.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static partial void TestWithModel(this StringBuilder builder, SomeModel model)
    {
        builder.Append(@"This is a more complex example with a parameter ");
        builder.Append( model.Value );
        builder.Append(@" and a second parameter ");
        builder.Append( model.Text );
    }
}
