//HintName: Test.TestWithParameter.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

public static partial class Test
{
    public static partial void TestWithParameter(this StringBuilder builder, Int32 param)
    {
        builder.Append(@"This is a more complex example with a parameter: ");
        builder.Append(param);
    }
}
