//HintName: Test.TestWithFileTemplate.wsr.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static void TestWithFileTemplate(this StringBuilder builder, string name, string whitespace)
    {
        builder.Append(@"# Hello ");
        builder.Append(Cutout.RenderUtilities.ApplyExtraWhitespace( name , whitespace));
        builder.Append(Cutout.RenderUtilities.ApplyExtraWhitespace(@"

This is a test!", whitespace));
    }
}
