//HintName: Test.TestWithTwoParameters.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static partial void TestWithTwoParameters(this StringBuilder builder, int param, string param2)
    {
        builder.Append(@"This is a more complex example with a parameter ");
        builder.Append( param );
        builder.Append(@" and a second parameter ");
        builder.Append( param2 );
    }
}
