//HintName: Test.TestWithModel.wsr.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static void TestWithModel(this StringBuilder builder, SomeModel model, string whitespace)
    {
        builder.Append(@"This is a more complex example with a parameter ");
        builder.Append( model.Value );
        if (( model.Value ).ToString().IndexOf('\n') != -1)
        {
            builder.Append(whitespace);
        }
        builder.Append(@" and a second parameter ");
        builder.Append( model.Text );
        if (( model.Text ).ToString().IndexOf('\n') != -1)
        {
            builder.Append(whitespace);
        }
    }
}
