//HintName: Test.TestWithFileTemplate.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static partial void TestWithFileTemplate(this StringBuilder builder, string name)
    {
        builder.Append(@"# Hello ");
        builder.Append( name );
        builder.Append(@"

This is a test!");
    }
}
