//HintName: Test.TestWithTwoParameters.wsr.g.cs
// <auto-generated/>
#nullable enable

using Cutout;
using System.Diagnostics.CodeAnalysis;
using System;

namespace <global namespace>;

internal static partial class Test
{
    internal static void TestWithTwoParameters(this StringBuilder builder, int param, string param2, string whitespace)
    {
        builder.Append(@"This is a more complex example with a parameter ");
        builder.Append(Cutout.RenderUtilities.ApplyExtraWhitespace( param , whitespace));
        builder.Append(@" and a second parameter ");
        builder.Append(Cutout.RenderUtilities.ApplyExtraWhitespace( param2 , whitespace));
    }
}
